accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),

    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

baibai/urls.py
from django.urls import path
from . import views

app_name = 'baibai'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('post/', views.CreateBaibaiView.as_view(), name='post'),

    path('post_done/',
         views.PostSuccessView.as_view(),
         name ='post_done'),

    path('baibais/<int:category>',
         views.CategoryView.as_view(),
         name ='baibai_cat'),

    path('user-list/<int:user>',
         views.UserView.as_view(),
         name ='user_list'),

    path('baibai-detail/<int:pk>',
         views.DetailView.as_view(),
         name ='baibai_detail'),

    path('mypage/',
         views.MypageView.as_view(),
         name='mypage'),

    path('baibai/<int:pk>/delete/',
         views.BaibaiDeleteView.as_view(),
         name ='baibai_delete'),

    path('baibai/<int:pk>/buy/',
         views.BaibaiBuyView.as_view(),
         name ='baibai_buy'),

    path('baibai/done/',
         views.BuySuccessView.as_view(),
         name ='baibai_done'),
]

baibaiproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('baibai.urls')),
    #''の所にpathと入れるとWebに表示させるとき127.0.0.1:8000/baibaiと表示される

    path('', include('accounts.urls')),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name = "password_reset.html"),
         name ='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name = "password_reset_sent.html"),
         name ='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name = "password_reset_done.html"),
         name ='password_reset_complate'),
]

# urlpatternsにmediaフォルダーのURLパターンを追加
urlpatterns += static(
   # MEDIA_URL = '/media/'
  settings.MEDIA_URL,
  # MEDIA_ROOTにリダイレクト
  document_root=settings.MEDIA_ROOT
  )

baibai/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(
        verbose_name='カテゴリ', 
        max_length=20)
    
    def __str__(self):
        return self.title

class BaibaiPost(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
        )

    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
        )
    
    title = models.CharField(
        verbose_name='タイトル', 
        max_length=200        
        )
    comment = models.TextField(
        verbose_name='コメント',  
        )
    money = models.PositiveIntegerField(
        verbose_name='値段',
        max_length=7,
    )
    # イメージのフィールド1
    image1 = models.ImageField(
        verbose_name='イメージ1',
        upload_to = 'baibais',    
        )
    # イメージのフィールド2
    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to = 'baibais',  
        blank=True,            
        null=True
        )        
    
    posted_at = models.DateTimeField(
        verbose_name='投稿日時', 
        auto_now_add=True       
        )
    
    def __str__(self):
        return self.title

baibai/forms.py
from django.forms import ModelForm
from .models import BaibaiPost

class BaibaiPostForm(ModelForm):
    '''ModelFormのサブクラス
    '''
    class Meta:
        '''ModelFormのインナークラス
        
        Attributes:
          model: モデルのクラス
          fields: フォームで使用するモデルのフィールドを指定
        '''
        model = BaibaiPost
        fields = ['category', 'title', 'comment', 'money', 'image1', 'image2']

baibai/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import BaibaiPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import BaibaiPost
from django.views.generic import DetailView
from django.views.generic import DeleteView


class IndexView(ListView):
    template_name ='index.html'
    queryset = BaibaiPost.objects.order_by('-posted_at')
    paginate_by = 9
@method_decorator(login_required, name='dispatch')

class CreateBaibaiView(CreateView):
    form_class = BaibaiPostForm
    template_name = "post_baibai.html"
    success_url = reverse_lazy('baibai:post_done')

    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    template_name ='post_success.html'

class CategoryView(ListView):
    template_name ='index.html'
    paginate_by = 9

    def get_queryset(self):
      category_id = self.kwargs['category']
      categories = BaibaiPost.objects.filter(
        category=category_id).order_by('-posted_at')
      return categories

class UserView(ListView):
    template_name ='index.html'
    paginate_by = 9

    def get_queryset(self):
      user_id = self.kwargs['user']
      user_list = BaibaiPost.objects.filter(
        user=user_id).order_by('-posted_at')
      return user_list

class DetailView(DetailView):
    template_name ='detail.html'
    model = BaibaiPost

class MypageView(ListView):
    template_name ='mypage.html'
    paginate_by = 9

    def get_queryset(self):
      queryset = BaibaiPost.objects.filter(
        user=self.request.user).order_by('-posted_at')
      return queryset
  
class BaibaiDeleteView(DeleteView):
    model = BaibaiPost
    template_name ='baibai_delete.html'
    success_url = reverse_lazy('baibai:mypage')
    def delete(self, request, *args, **kwargs):
      return super().delete(request, *args, **kwargs)
    
class BaibaiBuyView(ListView):
   template_name ='baibai_buy.html'
   model = BaibaiPost
   queryset = BaibaiPost.objects.order_by('-posted_at')
   success_url = reverse_lazy('baibai:baibai_done')

class BuySuccessView(TemplateView):
   template_name ='buy_success.html'

baibai/templates/baibai_buy.html
{% extends 'base.html' %}
{% block title %}Baibai Buy{% endblock %}

{% block contents %}
<br>
<div class="container">
  <div class="row">
    <div class="col offset-3">
      <form method="POST">
        <br>
        <p>購入しますか？</p>
        {% csrf_token %}
      </form>
      <a href="{% url 'baibai:baibai_done' %}">購入する</a>
      <a href="{% url 'baibai:index' %}">ホームに戻る</a>
    </div>
  </div>
</div>
{% endblock %}

baibai/templates/baibai_delete.html
{% extends 'base.html' %}
{% block title %}Baibai Detail{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
          <div class="col offset-3">
            <form method="POST">
              <br>
              <p>削除してもいいですか?</p>
              {% csrf_token %}
              <button class="btn btn-primary my-2"
                      type="submit">削除</button>
              <a href="{% url 'baibai:baibai_detail' object.pk %}"
                 class="btn btn-secondary my-2">キャンセル</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

baibai/templates/baibais_list.html
<div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for record in object_list %}

        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ record.image1.url }}"
                 class="bd-placeholder-img card-img-top"
                 width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg"
                 role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice"
                 focusable="false">
                 <title>Placeholder</title>
                 <rect width="100%" height="100%" fill="#55595c"/>
            </img>
            <div class="card-body">
              <p class="card-text">
                {{record.title}}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
  onclick="location.href='{% url 'baibai:baibai_detail' record.pk %}'">
                          詳細</button>
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
  onclick="location.href='{% url 'baibai:baibai_cat' category=record.category.id %}'">
                          {{record.category.title}}</button>
                          
                </div>
                <div>
                  <p class="card-text">
                    \{{record.money}}
                  </p>
                </div>
                <a href="{% url 'baibai:user_list' user=record.user.id %}">
                  <small class="text-muted">
                    {{record.user.username}}</small>
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  

baibai/templates/baibais_title.html
{% load static %}
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <img class="mb-4"
      src={% static "img1/mercari-logo-01-freelogovectors.net_.png" %}
      alt="" width="72"
      height="57">
      <h1 class="fw-light">Baibai Site</h1>
      <p class="lead text-muted">
        出品されている商品を探して欲しいものを買おう！
        いらなくなったものを売って欲しい人に届けよう！</p>
      <p>
        {% if user.is_authenticated %}
        <a href="{% url 'baibai:post' %}"
           class="btn btn-primary my-2">出品する</a>
        <a href="{% url 'accounts:logout' %}"
           class="btn btn-secondary my-2">ログアウト</a>
        {% else %}
        <a href="{% url 'accounts:signup' %}"
           class="btn btn-primary my-2">サインアップ</a>
        <a href="{% url 'accounts:login' %}"
           class="btn btn-secondary my-2">ログイン</a>
        {% endif %}
      </p>
    </div>
  </div>
</section>

baibai/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>{% block title %}{% endblock %}</title>


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">   


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

    </style>

    
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">お気に入りを見つけよう！</h4>
          <p class="text-muted">
            どなたでも手軽に出品できるサイトです。
            キーホルダーから電化製品までなんでも！

          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Contact</h4>
          <ul class="list-unstyled">
                <!-- ナビゲーションメニュー-->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="{% url 'baibai:mypage' %}"
                       class="text-white">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}"
                       class="text-white">ログアウト</a></li>
                <li><a href="{% url 'password_reset' %}"
                       class="text-white">パスワードのリセット</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">お問い合わせ</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}"
                       class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}"
                       class="text-white">ログイン</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">お問い合わせ</a></li>
                {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'baibai:index' %}" class="navbar-brand d-flex align-items-center">
        <strong>Baibai Site</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
  {% block contents %}{% endblock %}
</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Baibai Site is &copy; Bootstrap, but please post a lot!</p>
  </div>
</footer>
<script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

baibai/templates/buy_success.html
{% extends 'base.html' %}

{% block title %}Buy Success{% endblock %}

      {% block contents %}
      <br><br>
      <div class="container">
        <div class="row">
          <div class="col offset-2">
            <h4>購入が完了しました!</h4>  
          </dv>
        </dv>
      </dv>
      {% endblock %}

baibai/templates/detail.html
{% extends 'base.html' %}

{% block title %}Baibai Detail{% endblock %}

      {% block contents %}

      <br>
      <div class="container">
        <p>{{ object.pk }}</p>
        <div class="row">

          <div class="col offset-3">

            <h2>{{object.title}}</h2>

            <p>{{object.comment}}</p>
            <br>

            <p>{{object.posted_at}}に投稿</p>

            <p><img src="{{ object.image1.url }}"></img></p>

            {% if object.image2 %}
              <p><img src="{{ object.image2.url }}"></img></p>
            {% endif %}
            
            <a href="{% url 'baibai:baibai_buy' object.pk %}"
                class="btn btn-primary my-2">購入する</a>
            {% if request.user == object.user %}
            <form method="POST">

            <a href="{% url 'baibai:baibai_delete' object.pk %}"
               class="btn btn-primary my-2">削除する</a>
            {% endif %}
          </dv>
        </dv>
      </dv>
      {% endblock %}

baibai/templates/index.html
{% extends 'base.html' %}

{% block title %}Baibai Site{% endblock %}

        {% block contents %}
 
        {% include "baibais_title.html" %}
        
        {% include "baibais_list.html" %}

        {% include "pagination.html" %}
        
        {% endblock %}

baibai/templates/mypage.html
{% extends 'base.html' %}
{% block title %}Mypage{% endblock %}

      {% block contents %}

      {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
          <h4>商品一覧ページ</h4>
          {% if object_list.count == 0 %}
            <p>{{user.username}}さんの投稿はありません</p>
          {% else %}
            <p>投稿<strong>{{object_list.count}}</strong>件</p>
          {% endif %}
          <a href="{% url 'baibai:post' %}">出品する</a>
        </div>
        <hr>
      {% endif %}
      
      {% include "baibais_list.html" %}
        
      {% include "pagination.html" %}

      {% endblock %}

baibai/templates/pagination.html
<ul class="pagination"
    style="justify-content:center">

    {% if page_obj.has_previous %}

    <li class="page-item">
        <a class="page-link"
             href="?page={{ page_obj.previous_page_number }}"
             aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}

        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>

        {% else %}

        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}

    <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}"
           aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

baibai/templates/post_baibai.html
{% extends 'base.html' %}

{% block title %}Post{% endblock %}

      {% block contents %}

      <br>
      <div class="container">

        <div class="row">

          <div class="col offset-2">

            <form method="POST"
                  enctype="multipart/form-data">
              {% csrf_token %}
              <table>
                <tr>
                  <th>カテゴリ</th>
                  <td>{{ form.category }}</td>
                </tr>
                <tr>
                  <th>商品名</th>
                  <td>{{ form.title }}</td>
                </tr>
                <tr>
                  <th>商品の説明</th>
                  <td>{{ form.comment }}</td>
                </tr>
                  <th>値段</th>
                  <td>{{ form.money }}</td>
                <tr>
                  <th>画像1</th>
                  <td>{{ form.image1 }}</td>
                </tr>
                <tr>
                  <th>画像2</th>
                  <td>{{ form.image2 }}</td>
                </tr>
              </table>
              <hr>
              <button type="submit">出品する</button>
            </form>        
          </dv>
        </dv>
      </dv>
      {% endblock %}

baibai/templates/post_success.html
{% extends 'base.html' %}


{% block title %}Post Success{% endblock %}

      {% block contents %}
      <br><br>
      <div class="container">
        <div class="row">
          <div class="col offset-2">
            <h4>投稿が完了しました!</h4>  
          </dv>
        </dv>
      </dv>
      {% endblock %}